FROM python:3.9.21-alpine3.21 

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . .

# Set environment variables using build arguments
ARG DATABASE_URL
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_PORT
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_STORAGE_BUCKET_NAME
ARG AWS_S3_REGION_NAME
ARG CLOUDFRONT_URL
ARG DEFAULT_FILE_STORAGE
ARG VIRUSTOTAL_API_KEY

ENV DATABASE_URL=$DATABASE_URL
ENV DB_NAME=$DB_NAME
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME
ENV AWS_S3_REGION_NAME=$AWS_S3_REGION_NAME
ENV CLOUDFRONT_URL=$CLOUDFRONT_URL
ENV DEFAULT_FILE_STORAGE=$DEFAULT_FILE_STORAGE
ENV VIRUSTOTAL_API_KEY=$VIRUSTOTAL_API_KEY

RUN python manage.py migrate

# Expose the port the app runs on
EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]